Develop
outscale/butterfly pull request #389
Opened 2019-08-28 13:30 UTC by outscale-mgo

2020-01-02 13:16 UTC, outscale-fne requested changes
J'ai un peu titillé! Mais c'est surtout du formattage...

2020-01-02 13:16 UTC, outscale-fne commented on api/client/client.cc
> +                   string(argv[i]) == "--help") {
White space at the beginning of the line... Wrong indent :)

2020-01-02 13:16 UTC, outscale-fne commented on api/client/nic.cc
> +}
Why not incrementing indentation here?

2020-01-02 13:16 UTC, outscale-fne commented on api/common/vec.h
> +                     val;                                               \
Could be prettier if all `\` are in the same column...

2020-01-02 13:16 UTC, outscale-fne commented on api/protocol/message_0.proto
> +    //if type is benchmark, the kind of bebchmark you want to do
*benchmark

2020-01-02 13:16 UTC, outscale-fne commented on api/server/app.h
> +
Single new blank line?

2020-01-02 13:16 UTC, outscale-fne commented on api/server/graph.cc
> +    // printf("rx_snd_callback - %d - %d\n", bsnd->not_droped, len);
Commented code?

2020-01-02 13:16 UTC, outscale-fne commented on api/server/graph.cc
> +    // printf("pong\n");
Debug-related printf?

2020-01-02 13:16 UTC, outscale-fne commented on api/server/graph.cc
> +    // printf("Go %x !!!\n", binfo->ipdest);
Debug-related printf?

2020-01-02 13:16 UTC, outscale-fne commented on api/server/graph.cc
> +                                       &pkts_count, &poll_err) < 0)) {
Indentation error...

2020-01-02 14:27 UTC, outscale-mgo commented on api/client/client.cc
> +                   string(argv[i]) == "--help") {
I think in this case, the format was wrong before this code.
also, the white-space are not at the beginning of the line but after and before the newly added brace

2020-01-02 14:28 UTC, outscale-mgo commented on api/client/nic.cc
> +}
because google style ask not to

2020-01-06 13:29 UTC, outscale-toa approved these changes

2020-01-06 13:29 UTC, outscale-toa commented on tests/06_multiple_ipv4_on_nic/test.sh
> +
can you remove the white space please ?

2020-01-06 14:20 UTC, outscale-toa requested changes

2020-01-06 14:20 UTC, outscale-toa commented on tests/functions.sh
> +        sudo kill -s 0 ${server_pids[$id]} &> /dev/null
Can you do a loop or function to kill server_pids please?

2020-01-06 14:20 UTC, outscale-toa commented on tests/functions.sh
> +    exec sudo $BUTTERFLY_BUILD_ROOT/api/server/butterflyd --dpdk-args "--no-shconf -c1 -n1 --vdev=eth_pcap$id,iface=but$id --no-huge" -l debug -i ::101 -s /tmp --endpoint=tcp://0.0.0.0:876$id $option
Can you uncomment the output  file please?

2020-01-06 14:20 UTC, outscale-toa commented on tests/functions.sh
> +	echo 'FAIL !!!'
Why not 	```echo $CUR_TEST 'FAIL !!!' ```

2020-01-06 14:20 UTC, outscale-toa commented on tests/functions.sh
> +    exec $CMD &#> $BUTTERFLY_BUILD_ROOT/qemu_${id}_output &
Can you uncomment the log file please?

2020-01-09 09:24 UTC, merged